添加一些新功能和修复
FreezeYou/FreezeYou pull request #180
Opened 2021-03-21 14:22 UTC by shunf4

- 添加“强制停止应用”功能
  - 允许在单选和多选菜单中停止应用
  - 允许创建快捷方式停止一组自选应用
  - 允许使用 "fc -d xxx com.some.app" 任务停止一个或一组应用
- 添加更多的视图和排序方式
  - “未冻结的系统应用”视图
  - 按名称字母顺序排序
  - 按安装时间最新排序
- 更多快捷方式
  - 快速查看系统预装应用、用户应用、未冻结的系统应用
  - 快速查看我的自选
  - 允许停止一组自选应用
- 一些细节修复
  - 在应用刚启动时应该执行 `TasksUtils` 中的检查，避免被杀死后重新启动时未及时注册与定时任务相关的监听器等
  - 当 `apiMode` 为 `API_FREEZEYOU_LEGACY_AUTO`，执行 `oneKeyAction` 前应当决定一个具体的 apiMode，以便其使用 ROOT 模式的特殊处理，避免多次 `su`

2021-03-22 07:55 UTC, Playhi requested changes

2021-03-22 07:55 UTC, Playhi commented on app/src/main/java/cf/playhi/freezeyou/utils/ApplicationLabelUtils.java
> +
与15-44行相比除方法名外均相同，且该方法（getApplicationInstallTime）似乎并未被使用。
（这个整个PR的内容比较多，我需要大概几天时间抽时间复核）

2021-03-22 15:16 UTC, Playhi commented on app/src/main/java/cf/playhi/freezeyou/Main.java
> +            keyValuePair.put("InstallTime", packageInfo.firstInstallTime);
`firstInstallTime` 是首次安装时间，似乎 `lastUpdateTime` （最后更新（安装）时间）也符合 ***按安装时间最新排序*** （此处是否有误用或表述偏差）

2021-03-22 15:16 UTC, Playhi commented on app/src/main/java/cf/playhi/freezeyou/Main.java
> +        TasksUtils.checkTriggerTasks(this);
这个加在 MainApplication 中或许更好些？

2021-03-22 15:16 UTC, Playhi commented on app/src/main/java/cf/playhi/freezeyou/Main.java
> +                installTime = pi.firstInstallTime;
同上述
> firstInstallTime 是首次安装时间，似乎 lastUpdateTime （最后更新（安装）时间）也符合 按安装时间最新排序 （此处是否有误用或表述偏差）

2021-03-23 12:34 UTC, Playhi requested changes

2021-03-23 12:34 UTC, Playhi commented on app/src/main/java/cf/playhi/freezeyou/ForceStop.java
> +        if (pkgName.startsWith("FORCESTOPCATEGORY")) {
`pkgName`未判空

2021-03-23 12:34 UTC, Playhi commented on app/src/main/java/cf/playhi/freezeyou/ForceStop.java
> +public class ForceStop extends FreezeYouBaseActivity {
全部交由`ForceStopService`处理或许会更好些？这个`Activity`似乎不是很有必要～

2021-03-23 12:41 UTC, Playhi requested changes

2021-03-23 12:41 UTC, Playhi commented on app/src/main/java/cf/playhi/freezeyou/ForceStopService.java
> +            startForeground(4, new Notification());
`id`与`FUFService`中的重复了

2021-03-23 12:41 UTC, Playhi commented on app/src/main/java/cf/playhi/freezeyou/ForceStopService.java
> +        AppPreferences appPreferences = new AppPreferences(context);
变量`appPreferences`未被使用

2021-03-26 14:13 UTC, Playhi commented
以后要是还有在什么项目里（包括但不限于这次这个）提PR，我这边建议尽量还是每个功能分别单独提交PR吧，这样写好一个功能就能发起一个PR（更快），合并前复核的时候也更方便（每次需要检查的代码量不会太大），合并也能够更快（单个PR没问题或问题修正完毕就可以先合并进入了） :joy:

2021-05-15 09:19 UTC, shunf4 commented on app/src/main/java/cf/playhi/freezeyou/Main.java
> +            keyValuePair.put("InstallTime", packageInfo.firstInstallTime);
我个人会更愿意按首次安装时间排序，不太希望看到谷歌市场或者 F-Droid 自动更新某一应用后这个应用突然就排在第一个了。

2021-05-15 09:26 UTC, shunf4 commented on app/src/main/java/cf/playhi/freezeyou/Main.java
> +        TasksUtils.checkTriggerTasks(this);
我看 updateFrozenStatusBroadcastReceiver 也是在 Main#go 里注册的，放这里比较统一吧

2021-05-15 09:29 UTC, shunf4 commented on app/src/main/java/cf/playhi/freezeyou/ForceStop.java
> +public class ForceStop extends FreezeYouBaseActivity {
创建强制停止应用的快捷方式时，需要兼容 checkSettingsAndRequestCreateShortcut，这个方法接受的 cls 必须是一个 Activity

2021-05-15 10:21 UTC, Playhi commented on app/src/main/java/cf/playhi/freezeyou/Main.java
> +                installTime = pi.firstInstallTime;
在上一处解答过了。_（Resolve conversation）_
> 我个人会更愿意按首次安装时间排序，不太希望看到谷歌市场或者 F-Droid 自动更新某一应用后这个应用突然就排在第一个了。

2021-05-15 11:12 UTC, shunf4 commented on app/src/main/java/cf/playhi/freezeyou/utils/ApplicationLabelUtils.java
> +
已经删除

2021-05-15 11:12 UTC, shunf4 commented on app/src/main/java/cf/playhi/freezeyou/ForceStop.java
> +        if (pkgName.startsWith("FORCESTOPCATEGORY")) {
已添加判空

2021-05-15 11:13 UTC, shunf4 commented on app/src/main/java/cf/playhi/freezeyou/ForceStopService.java
> +            startForeground(4, new Notification());
已改为6

2021-05-15 11:13 UTC, shunf4 commented on app/src/main/java/cf/playhi/freezeyou/ForceStopService.java
> +        AppPreferences appPreferences = new AppPreferences(context);
已删除

2021-05-15 12:25 UTC, Playhi commented on app/src/main/java/cf/playhi/freezeyou/Main.java
> +        TasksUtils.checkTriggerTasks(this);
updateFrozenStatusBroadcastReceiver 是因为只有在 Main.java 里有需要（有冻结解冻状态点） :joy:

2021-05-15 12:49 UTC, shunf4 commented on app/src/main/java/cf/playhi/freezeyou/Main.java
> +        TasksUtils.checkTriggerTasks(this);
谷歌禁止在 API 26 以上用 `Application` 来做 `startService`。所以恐怕还是要从 `Main` Activity 里来做。

https://stackoverflow.com/questions/12381977/starting-a-service-from-application-class
https://developer.android.com/guide/components/services#StartingAService

2021-05-15 13:33 UTC, Playhi commented on app/src/main/res/values/strings.xml
> +    <string name="forceStopMyCustomization">Force stop my customation</string>
拼写有问题，问题不大，可以合并以后我再改，就先不针对这个问题发起新的 Review 了。（别的内容还需要些时间看）

2021-05-15 14:12 UTC, Playhi commented on app/src/main/java/cf/playhi/freezeyou/Main.java
> +        TasksUtils.checkTriggerTasks(this);
噗，没注意到触发器里还有两个用到 Service 了，那就先这样吧

2021-05-16 05:12 UTC, Playhi commented
有空给个称呼吧（比如 shunf4），还可以给个关联链接（比如 https://github.com/shunf4 ），后续会用在诸如感谢名单这类的地方。还有一部分内容在抽空复核，估计这两天能完成合并了，很感谢这次的 PR。 :heart:

2021-05-16 05:37 UTC, shunf4 commented
shunf4 和 https://github.com/shunf4 就好

2021-05-18 13:01 UTC, Playhi approved these changes
import 还有些多余的，不管这些了（没啥大问题），合并啦～

2021-05-18 13:16 UTC, merged